### PR TITLE
Add task to move prefixed action templates

### PR DESCRIPTION
**Pull request by ceeram**

### CODE REVIEW

**Comment by markstory** [comment]
Nice work :+1:

**Comment by ceeram** [comment]
Oops forgot to include description

Move view templates for prefixed actions to correct location.
Planning to add another task to extract prefixed actions from controller and move it to new controller in prefix subdir, when i find the time for it

**Comment by ceeram** [comment]
No merge yet please, seems to be something wrong with locations

**Comment by ceeram** [comment]
nvm, it was not caused by this task, something else already created src/src/Template folder, must have been something in locations command, as that was the only one i had run on this 2.x project before testing the prefixed_action task

**Comment by ceeram** [comment]
Will add some info to the readme as well for this, by default this runs for admin prefix, but can be run for any prefix if needed.

**Pull request merged**
