### PR TITLE
Add return values for Command::execute()

### PR DESCRIPTION
**Pull request by markstory**
Part of the steps we have in the [5.0 roadmap](https://github.com/cakephp/cakephp/wiki/5.0-Roadmap).

### CODE REVIEW

**Comment by ADmad** [comment]
Now that we have a rector rule can we resurrect https://github.com/cakephp/cakephp/pull/16609?

**Comment by LordSimal** [comment]
Not really sure we can do this with rector but not all commands out there will have `return self::CODE_SUCCESS;` inside them.
Or do we expect users to add that themselves after upgrading?

**Comment by ADmad** [comment]
Ah I misunderstood what this rule does. It only adds the return type, not the actual return statement.

**Comment by markstory** [comment]
Modifying the existing command classes to add a return code is also on our list. I can try getting that implemented via rector as well later this week.

**Pull request merged**
