### PR TITLE
Lock rector to 0.9.*

### LINKED ISSUE #164: Issue running rector on the src files
Hello,

When running `bin/cake upgrade rector --rules cakephp40 /var/www/html/` I get the following error:

`PHP Fatal error: During class fetch: Uncaught PHPStan\Broker\ClassAutoloadingException: Class Cake\ORM\Locator\LocatorAwareTrait not found.`

### PR DESCRIPTION
**Pull request by robertpustulka**
Should fix #164

### CODE REVIEW

**Comment by othercorey** [comment]
I didn't have any issue testing with 0.10 locally.

**Comment by robertpustulka** [comment]
Maybe it is specific to codeset. I've run into this and figured out locking rector to 0.9 let me through. Include the fix if you want, I have resolved my issue with this locally already.

**Comment by othercorey** [comment]
@markstory We need to figure out what test is missing here.

**Comment by othercorey** [comment]
@robertpustulka Are you able to test latest master? I don't know how else to check if rector is still causing your issue now that we've had to upgrade to 0.10.x.

Is it at all possible to share some of the app code it bails on -- if you can tell?

**Pull request closed without merging**
